/******************************************************************************
Automatically generated header for DCC data
Generated by DCC generator ver 0.1.10
for dcc_descriptor_id_type = UNKNOWN
vendor ID 1
******************************************************************************/

#ifndef __MCTNF_CONFIG_DCC_H__ 
#define __MCTNF_CONFIG_DCC_H__

#include "fw_to_dcc.h"

typedef struct {
    uint8 update;
    uint8 enable;
    uint8 blending_factor_q4;
    uint8 min_blend_q4;
    uint8 max_blend_q4;
    uint8 me_lambda_type;
    uint8 me_lambda_factor_q2;
    uint8 max_lambda_q2;
    uint16 sad_for_min_lambda;
    uint16 fix_wt_cur_q8;
    uint8 bias_zero_motion;
    uint8 static_mb_th_zero_mv;
    uint8 static_mb_th_non_zero_mv;
    uint8 blockiness_rem_factor;
    uint16 me_effectiveness_th;
    uint8 min_wt_cur_q8;
    uint16 sad_max_strength;
    uint16 reserved_param1;
    uint16 reserved_param2;
    uint16 reserved_param3;
} mctnf_cfg_dcc_descriptor_t;

int mctnf_config_dcc_dcc_bin_parse(uint8* b_sys_prm, uint8* b_uc_prm, uint8* b_parpack,
                  void* sys_prm, void* uc_prm, void* parpack,
                  uint32 crc);
void mctnf_config_dcc_dcc_bin_free(void* sys_prm, void* uc_prm, void* parpack);

#endif

