/* 
 * This file is AUTO GENERATED by PyTI_PSDK_RTOS tool. 
 * It is NOT recommended to manually edit this file 
 */ 
/* 
 * 
 * Copyright (c) 2018 Texas Instruments Incorporated 
 * 
 * All rights reserved not granted herein. 
 * 
 * Limited License. 
 * 
 * Texas Instruments Incorporated grants a world-wide, royalty-free, non-exclusive 
 * license under copyrights and patents it now or hereafter owns or controls to make, 
 * have made, use, import, offer to sell and sell ("Utilize") this software subject to the 
 * terms herein.  With respect to the foregoing patent license, such license is granted 
 * solely to the extent that any such patent is necessary to Utilize the software alone. 
 * The patent license shall not apply to any combinations which include this software, 
 * other than combinations with devices manufactured by or for TI ("TI Devices"). 
 * No hardware patent is licensed hereunder. 
 * 
 * Redistributions must preserve existing copyright notices and reproduce this license 
 * (including the above copyright notice and the disclaimer and (if applicable) source 
 * code license limitations below) in the documentation and/or other materials provided 
 * with the distribution 
 * 
 * Redistribution and use in binary form, without modification, are permitted provided 
 * that the following conditions are met: 
 * 
 *        No reverse engineering, decompilation, or disassembly of this software is 
 * permitted with respect to any software provided in binary form. 
 * 
 *        any redistribution and use are licensed by TI for use only with TI Devices. 
 * 
 *        Nothing shall obligate TI to provide you with source code for the software 
 * licensed and provided to you in object code. 
 * 
 * If software source code is provided to you, modification and redistribution of the 
 * source code are permitted provided that the following conditions are met: 
 * 
 *        any redistribution and use of the source code, including any resulting derivative 
 * works, are licensed by TI for use only with TI Devices. 
 * 
 *        any redistribution and use of any object code compiled from the source code 
 * and any resulting derivative works, are licensed by TI for use only with TI Devices. 
 * 
 * Neither the name of Texas Instruments Incorporated nor the names of its suppliers 
 * 
 * may be used to endorse or promote products derived from this software without 
 * specific prior written permission. 
 * 
 * DISCLAIMER. 
 * 
 * THIS SOFTWARE IS PROVIDED BY TI AND TI'S LICENSORS "AS IS" AND ANY EXPRESS 
 * OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES 
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. 
 * IN NO EVENT SHALL TI AND TI'S LICENSORS BE LIABLE FOR ANY DIRECT, INDIRECT, 
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, 
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, 
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY 
 * OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE 
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED 
 * OF THE POSSIBILITY OF SUCH DAMAGE. 
 * 
 */ 
#ifndef APP_MEM_MAP_H
#define APP_MEM_MAP_H


/* L2 for C66x_1 [ size 224.00 KB ] */
#define L2RAM_C66x_1_ADDR (0x00800000u)
#define L2RAM_C66x_1_SIZE (0x00038000u)

/* L2 for C66x_2 [ size 224.00 KB ] */
#define L2RAM_C66x_2_ADDR (0x00800000u)
#define L2RAM_C66x_2_SIZE (0x00038000u)

/* Main OCRAM for MCU2_0 [ size 256.00 KB ] */
#define MAIN_OCRAM_MCU2_0_ADDR (0x03600000u)
#define MAIN_OCRAM_MCU2_0_SIZE (0x00040000u)

/* Main OCRAM for MCU2_1 [ size 256.00 KB ] */
#define MAIN_OCRAM_MCU2_1_ADDR (0x03640000u)
#define MAIN_OCRAM_MCU2_1_SIZE (0x00040000u)

/* L2 for C7x_1 [ size 448.00 KB ] */
#define L2RAM_C7x_1_ADDR (0x64800000u)
#define L2RAM_C7x_1_SIZE (0x00070000u)

/* L1 for C7x_1 [ size 16.00 KB ] */
#define L1RAM_C7x_1_ADDR (0x64E00000u)
#define L1RAM_C7x_1_SIZE (0x00004000u)

/* MSMC for C7x_1 [ size  7.78 MB ] */
#define MSMC_C7x_1_ADDR (0x70020000u)
#define MSMC_C7x_1_SIZE (0x007C8000u)

/* DDR for MCU1_0 for Linux IPC [ size 1024.00 KB ] */
#define DDR_MCU1_0_IPC_ADDR (0xA0000000u)
#define DDR_MCU1_0_IPC_SIZE (0x00100000u)

/* DDR for MCU1_0 for all sections, used for reserving memory in DTS file [ size 15.00 MB ] */
#define DDR_MCU1_0_DTS_ADDR (0xA0100000u)
#define DDR_MCU1_0_DTS_SIZE (0x00F00000u)

/* DDR for MCU1_1 for Linux IPC [ size 1024.00 KB ] */
#define DDR_MCU1_1_IPC_ADDR (0xA1000000u)
#define DDR_MCU1_1_IPC_SIZE (0x00100000u)

/* DDR for MCU1_1 for all sections, used for reserving memory in DTS file [ size 15.00 MB ] */
#define DDR_MCU1_1_DTS_ADDR (0xA1100000u)
#define DDR_MCU1_1_DTS_SIZE (0x00F00000u)

/* DDR for MCU2_0 for Linux IPC [ size 1024.00 KB ] */
#define DDR_MCU2_0_IPC_ADDR (0xA2000000u)
#define DDR_MCU2_0_IPC_SIZE (0x00100000u)

/* DDR for MCU2_0 for all sections, used for reserving memory in DTS file [ size 31.00 MB ] */
#define DDR_MCU2_0_DTS_ADDR (0xA2100000u)
#define DDR_MCU2_0_DTS_SIZE (0x01F00000u)

/* DDR for MCU2_1 for Linux IPC [ size 1024.00 KB ] */
#define DDR_MCU2_1_IPC_ADDR (0xA4000000u)
#define DDR_MCU2_1_IPC_SIZE (0x00100000u)

/* DDR for MCU2_1 for all sections, used for reserving memory in DTS file [ size 31.00 MB ] */
#define DDR_MCU2_1_DTS_ADDR (0xA4100000u)
#define DDR_MCU2_1_DTS_SIZE (0x01F00000u)

/* DDR for MCU3_0 for Linux IPC [ size 1024.00 KB ] */
#define DDR_MCU3_0_IPC_ADDR (0xA6000000u)
#define DDR_MCU3_0_IPC_SIZE (0x00100000u)

/* DDR for MCU3_0 for all sections, used for reserving memory in DTS file [ size 15.00 MB ] */
#define DDR_MCU3_0_DTS_ADDR (0xA6100000u)
#define DDR_MCU3_0_DTS_SIZE (0x00F00000u)

/* DDR for MCU3_1 for Linux IPC [ size 1024.00 KB ] */
#define DDR_MCU3_1_IPC_ADDR (0xA7000000u)
#define DDR_MCU3_1_IPC_SIZE (0x00100000u)

/* DDR for MCU3_1 for all sections, used for reserving memory in DTS file [ size 15.00 MB ] */
#define DDR_MCU3_1_DTS_ADDR (0xA7100000u)
#define DDR_MCU3_1_DTS_SIZE (0x00F00000u)

/* DDR for C66x_2 for Linux IPC [ size 1024.00 KB ] */
#define DDR_C66x_2_IPC_ADDR (0xA8000000u)
#define DDR_C66x_2_IPC_SIZE (0x00100000u)

/* DDR for C66x_1 for all sections, used for reserving memory in DTS file [ size 15.00 MB ] */
#define DDR_C66x_1_DTS_ADDR (0xA8100000u)
#define DDR_C66x_1_DTS_SIZE (0x00F00000u)

/* DDR for C66x_1 for Linux IPC [ size 1024.00 KB ] */
#define DDR_C66x_1_IPC_ADDR (0xA9000000u)
#define DDR_C66x_1_IPC_SIZE (0x00100000u)

/* DDR for C66x_2 for all sections, used for reserving memory in DTS file [ size 15.00 MB ] */
#define DDR_C66x_2_DTS_ADDR (0xA9100000u)
#define DDR_C66x_2_DTS_SIZE (0x00F00000u)

/* Memory for IPC Vring's. MUST be non-cached or cache-coherent [ size 32.00 MB ] */
#define IPC_VRING_MEM_ADDR (0xAA000000u)
#define IPC_VRING_MEM_SIZE (0x02000000u)

/* Memory for remote core logging [ size 256.00 KB ] */
#define APP_LOG_MEM_ADDR (0xAC000000u)
#define APP_LOG_MEM_SIZE (0x00040000u)

/* Memory for TI OpenVX shared memory. MUST be non-cached or cache-coherent [ size 63.75 MB ] */
#define TIOVX_OBJ_DESC_MEM_ADDR (0xAC040000u)
#define TIOVX_OBJ_DESC_MEM_SIZE (0x03FC0000u)

/* Memory for TI OpenVX shared memory for Run-time logging. MUST be non-cached or cache-coherent [ size 32.00 MB ] */
#define TIOVX_LOG_RT_MEM_ADDR (0xB0000000u)
#define TIOVX_LOG_RT_MEM_SIZE (0x02000000u)

/* DDR for C7x_1 for Linux IPC [ size 1024.00 KB ] */
#define DDR_C7x_1_IPC_ADDR (0xB2000000u)
#define DDR_C7x_1_IPC_SIZE (0x00100000u)

/* DDR for C7x_1 for all sections, used for reserving memory in DTS file [ size 95.00 MB ] */
#define DDR_C7x_1_DTS_ADDR (0xB2100000u)
#define DDR_C7x_1_DTS_SIZE (0x05F00000u)

/* Memory for shared memory buffers in DDR [ size 512.00 MB ] */
#define DDR_SHARED_MEM_ADDR (0xB8000000u)
#define DDR_SHARED_MEM_SIZE (0x20000000u)

/* DDR for MCU1_0 for local heap [ size  8.00 MB ] */
#define DDR_MCU1_0_LOCAL_HEAP_ADDR (0xD8000000u)
#define DDR_MCU1_0_LOCAL_HEAP_SIZE (0x00800000u)

/* DDR for MCU1_1 for local heap [ size  8.00 MB ] */
#define DDR_MCU1_1_LOCAL_HEAP_ADDR (0xD8800000u)
#define DDR_MCU1_1_LOCAL_HEAP_SIZE (0x00800000u)

/* DDR for MCU2_0 for local heap [ size 16.00 MB ] */
#define DDR_MCU2_0_LOCAL_HEAP_ADDR (0xD9000000u)
#define DDR_MCU2_0_LOCAL_HEAP_SIZE (0x01000000u)

/* DDR for MCU2_1 for local heap [ size 16.00 MB ] */
#define DDR_MCU2_1_LOCAL_HEAP_ADDR (0xDA000000u)
#define DDR_MCU2_1_LOCAL_HEAP_SIZE (0x01000000u)

/* DDR for MCU3_0 for local heap [ size  8.00 MB ] */
#define DDR_MCU3_0_LOCAL_HEAP_ADDR (0xDB000000u)
#define DDR_MCU3_0_LOCAL_HEAP_SIZE (0x00800000u)

/* DDR for MCU3_1 for local heap [ size  8.00 MB ] */
#define DDR_MCU3_1_LOCAL_HEAP_ADDR (0xDB800000u)
#define DDR_MCU3_1_LOCAL_HEAP_SIZE (0x00800000u)

/* DDR for c66x_1 for local heap [ size 16.00 MB ] */
#define DDR_C66X_1_LOCAL_HEAP_ADDR (0xDC000000u)
#define DDR_C66X_1_LOCAL_HEAP_SIZE (0x01000000u)

/* DDR for c66x_1 for Scratch Memory [ size 48.00 MB ] */
#define DDR_C66X_1_SCRATCH_ADDR (0xDD000000u)
#define DDR_C66X_1_SCRATCH_SIZE (0x03000000u)

/* DDR for c66x_2 for local heap [ size 16.00 MB ] */
#define DDR_C66X_2_LOCAL_HEAP_ADDR (0xE0000000u)
#define DDR_C66X_2_LOCAL_HEAP_SIZE (0x01000000u)

/* DDR for c66x_2 for Scratch Memory [ size 48.00 MB ] */
#define DDR_C66X_2_SCRATCH_ADDR (0xE1000000u)
#define DDR_C66X_2_SCRATCH_SIZE (0x03000000u)

/* Inter-core ethernet shared desc queues. MUST be non-cached or cache-coherent [ size  8.00 MB ] */
#define INTERCORE_ETH_DESC_MEM_ADDR (0xE4000000u)
#define INTERCORE_ETH_DESC_MEM_SIZE (0x00800000u)

/* Inter-core ethernet shared data buffers. MUST be non-cached or cache-coherent [ size 24.00 MB ] */
#define INTERCORE_ETH_DATA_MEM_ADDR (0xE4800000u)
#define INTERCORE_ETH_DATA_MEM_SIZE (0x01800000u)

/* DDR for c7x_1 for Scratch Memory [ size 368.00 MB ] */
#define DDR_C7X_1_SCRATCH_ADDR (0x100000000u)
#define DDR_C7X_1_SCRATCH_SIZE (0x17000000u)

/* DDR for c7x_1 for local heap [ size 256.00 MB ] */
#define DDR_C7X_1_LOCAL_HEAP_ADDR (0x117000000u)
#define DDR_C7X_1_LOCAL_HEAP_SIZE (0x10000000u)

#define DDR_64BIT_BASE_VADDR (0x100000000u)
#define DDR_64BIT_BASE_PADDR (0x880000000u)

#endif /* APP_MEM_MAP_H */

