/* 
 * This file is AUTO GENERATED by PyTI_PSDK_RTOS tool. 
 * It is NOT recommended to manually edit this file 
 */ 
/* 
 * 
 * Copyright (c) 2018 Texas Instruments Incorporated 
 * 
 * All rights reserved not granted herein. 
 * 
 * Limited License. 
 * 
 * Texas Instruments Incorporated grants a world-wide, royalty-free, non-exclusive 
 * license under copyrights and patents it now or hereafter owns or controls to make, 
 * have made, use, import, offer to sell and sell ("Utilize") this software subject to the 
 * terms herein.  With respect to the foregoing patent license, such license is granted 
 * solely to the extent that any such patent is necessary to Utilize the software alone. 
 * The patent license shall not apply to any combinations which include this software, 
 * other than combinations with devices manufactured by or for TI ("TI Devices"). 
 * No hardware patent is licensed hereunder. 
 * 
 * Redistributions must preserve existing copyright notices and reproduce this license 
 * (including the above copyright notice and the disclaimer and (if applicable) source 
 * code license limitations below) in the documentation and/or other materials provided 
 * with the distribution 
 * 
 * Redistribution and use in binary form, without modification, are permitted provided 
 * that the following conditions are met: 
 * 
 *        No reverse engineering, decompilation, or disassembly of this software is 
 * permitted with respect to any software provided in binary form. 
 * 
 *        any redistribution and use are licensed by TI for use only with TI Devices. 
 * 
 *        Nothing shall obligate TI to provide you with source code for the software 
 * licensed and provided to you in object code. 
 * 
 * If software source code is provided to you, modification and redistribution of the 
 * source code are permitted provided that the following conditions are met: 
 * 
 *        any redistribution and use of the source code, including any resulting derivative 
 * works, are licensed by TI for use only with TI Devices. 
 * 
 *        any redistribution and use of any object code compiled from the source code 
 * and any resulting derivative works, are licensed by TI for use only with TI Devices. 
 * 
 * Neither the name of Texas Instruments Incorporated nor the names of its suppliers 
 * 
 * may be used to endorse or promote products derived from this software without 
 * specific prior written permission. 
 * 
 * DISCLAIMER. 
 * 
 * THIS SOFTWARE IS PROVIDED BY TI AND TI'S LICENSORS "AS IS" AND ANY EXPRESS 
 * OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES 
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. 
 * IN NO EVENT SHALL TI AND TI'S LICENSORS BE LIABLE FOR ANY DIRECT, INDIRECT, 
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, 
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, 
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY 
 * OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE 
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED 
 * OF THE POSSIBILITY OF SUCH DAMAGE. 
 * 
 */ 
#ifndef APP_MEM_MAP_H
#define APP_MEM_MAP_H


/* L3 for C7x_1 [ size 1024.00 KB ] */
#define L2RAM_C7x_1_MAIN_ADDR (0x7E000000u)
#define L2RAM_C7x_1_MAIN_SIZE (0x00100000u)

/* L2 for C7x_1 [ size 240.00 KB ] */
#define L2RAM_C7x_1_AUX_ADDR (0x7F000000u)
#define L2RAM_C7x_1_AUX_SIZE (0x0003C000u)

/* L1 for C7x_1 [ size 16.00 KB ] */
#define L2RAM_C7x_1_AUX_AS_L1_ADDR (0x7F03C000u)
#define L2RAM_C7x_1_AUX_AS_L1_SIZE (0x00004000u)

/* DDR for C7x_1 for Linux IPC [ size 1024.00 KB ] */
#define DDR_C7x_1_IPC_ADDR (0x99800000u)
#define DDR_C7x_1_IPC_SIZE (0x00100000u)

/* DDR for C7x_1 for all sections, used for reserving memory in DTS file [ size 31.00 MB ] */
#define DDR_C7x_1_DTS_ADDR (0x99900000u)
#define DDR_C7x_1_DTS_SIZE (0x01F00000u)

/* DDR for MCU R5F for Linux IPC [ size 1024.00 KB ] */
#define DDR_MCU_R5F_IPC_ADDR (0x9B800000u)
#define DDR_MCU_R5F_IPC_SIZE (0x00100000u)

/* DDR for MCU R5F for all sections, used for reserving memory in DTS file [ size 15.00 MB ] */
#define DDR_MCU_R5F_DTS_ADDR (0x9B900000u)
#define DDR_MCU_R5F_DTS_SIZE (0x00F00000u)

/* DDR for DM R5F for Linux IPC [ size 1024.00 KB ] */
#define DDR_DM_R5F_IPC_ADDR (0x9C800000u)
#define DDR_DM_R5F_IPC_SIZE (0x00100000u)

/* DDR for DM R5F for all sections, used for reserving memory in DTS file [ size 30.00 MB ] */
#define DDR_DM_R5F_DTS_ADDR (0x9C900000u)
#define DDR_DM_R5F_DTS_SIZE (0x01E00000u)

/* Memory for IPC Vring's. MUST be non-cached or cache-coherent [ size 16.00 MB ] */
#define IPC_VRING_MEM_ADDR (0xA0000000u)
#define IPC_VRING_MEM_SIZE (0x01000000u)

/* Memory for remote core logging [ size 256.00 KB ] */
#define APP_LOG_MEM_ADDR (0xA1000000u)
#define APP_LOG_MEM_SIZE (0x00040000u)

/* Memory for TI OpenVX shared memory. MUST be non-cached or cache-coherent [ size 15.75 MB ] */
#define TIOVX_OBJ_DESC_MEM_ADDR (0xA1040000u)
#define TIOVX_OBJ_DESC_MEM_SIZE (0x00FC0000u)

/* Memory for TI OpenVX shared memory for Run-time logging. MUST be non-cached or cache-coherent [ size 16.00 MB ] */
#define TIOVX_LOG_RT_MEM_ADDR (0xA2000000u)
#define TIOVX_LOG_RT_MEM_SIZE (0x01000000u)

/* Memory for shared memory buffers in DDR [ size 176.00 MB ] */
#define DDR_SHARED_MEM_ADDR (0xA3000000u)
#define DDR_SHARED_MEM_SIZE (0x0B000000u)

/* DDR for MCU R5F for local heap [ size 16.00 MB ] */
#define DDR_MCU_R5F_LOCAL_HEAP_ADDR (0xAE000000u)
#define DDR_MCU_R5F_LOCAL_HEAP_SIZE (0x01000000u)

/* DDR for DM R5F for local heap [ size 16.00 MB ] */
#define DDR_DM_R5F_LOCAL_HEAP_ADDR (0xAF000000u)
#define DDR_DM_R5F_LOCAL_HEAP_SIZE (0x01000000u)

/* DDR for c7x_1 for non cacheable local heap [ size 16.00 MB ] */
#define DDR_C7X_1_LOCAL_HEAP_NON_CACHEABLE_ADDR (0xB0000000u)
#define DDR_C7X_1_LOCAL_HEAP_NON_CACHEABLE_SIZE (0x01000000u)

/* DDR for c7x_1 for non cacheable scratch Memory [ size 16.00 MB ] */
#define DDR_C7X_1_SCRATCH_NON_CACHEABLE_ADDR (0xB1000000u)
#define DDR_C7X_1_SCRATCH_NON_CACHEABLE_SIZE (0x01000000u)

/* DDR for c7x_1 for local heap [ size 112.00 MB ] */
#define DDR_C7X_1_LOCAL_HEAP_ADDR (0xB2000000u)
#define DDR_C7X_1_LOCAL_HEAP_SIZE (0x07000000u)

/* DDR for c7x_1 for Scratch Memory [ size 112.00 MB ] */
#define DDR_C7X_1_SCRATCH_ADDR (0xB9000000u)
#define DDR_C7X_1_SCRATCH_SIZE (0x07000000u)

#define DDR_64BIT_BASE_VADDR (0x00000000u)
#define DDR_64BIT_BASE_PADDR (0x00000000u)

#endif /* APP_MEM_MAP_H */

