#
# Copyright (c) 2018 Texas Instruments Incorporated
#
# All rights reserved not granted herein.
#
# Limited License.
#
# Texas Instruments Incorporated grants a world-wide, royalty-free, non-exclusive
# license under copyrights and patents it now or hereafter owns or controls to make,
# have made, use, import, offer to sell and sell ("Utilize") this software subject to the
# terms herein.  With respect to the foregoing patent license, such license is granted
# solely to the extent that any such patent is necessary to Utilize the software alone.
# The patent license shall not apply to any combinations which include this software,
# other than combinations with devices manufactured by or for TI ("TI Devices").
# No hardware patent is licensed hereunder.
#
# Redistributions must preserve existing copyright notices and reproduce this license
# (including the above copyright notice and the disclaimer and (if applicable) source
# code license limitations below) in the documentation and/or other materials provided
# with the distribution
#
# Redistribution and use in binary form, without modification, are permitted provided
# that the following conditions are met:
#
#       No reverse engineering, decompilation, or disassembly of this software is
# permitted with respect to any software provided in binary form.
#
#       any redistribution and use are licensed by TI for use only with TI Devices.
#
#       Nothing shall obligate TI to provide you with source code for the software
# licensed and provided to you in object code.
#
# If software source code is provided to you, modification and redistribution of the
# source code are permitted provided that the following conditions are met:
#
#       any redistribution and use of the source code, including any resulting derivative
# works, are licensed by TI for use only with TI Devices.
#
#       any redistribution and use of any object code compiled from the source code
# and any resulting derivative works, are licensed by TI for use only with TI Devices.
#
# Neither the name of Texas Instruments Incorporated nor the names of its suppliers
#
# may be used to endorse or promote products derived from this software without
# specific prior written permission.
#
# DISCLAIMER.
#
# THIS SOFTWARE IS PROVIDED BY TI AND TI'S LICENSORS "AS IS" AND ANY EXPRESS
# OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
# OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
# IN NO EVENT SHALL TI AND TI'S LICENSORS BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
# OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
# OF THE POSSIBILITY OF SUCH DAMAGE.
#
#

import os, sys, re
from . import *

class Common : 
    tiCopyrightHeader = "" \
     "/* \n" \
     " * This file is AUTO GENERATED by PyTI_PSDK_RTOS tool. \n" \
     " * It is NOT recommended to manually edit this file \n" \
     " */ \n" \
     "/* \n" \
     " * \n" \
     " * Copyright (c) 2018 Texas Instruments Incorporated \n" \
     " * \n" \
     " * All rights reserved not granted herein. \n" \
     " * \n" \
     " * Limited License. \n" \
     " * \n" \
     " * Texas Instruments Incorporated grants a world-wide, royalty-free, non-exclusive \n" \
     " * license under copyrights and patents it now or hereafter owns or controls to make, \n" \
     " * have made, use, import, offer to sell and sell (\"Utilize\") this software subject to the \n" \
     " * terms herein.  With respect to the foregoing patent license, such license is granted \n" \
     " * solely to the extent that any such patent is necessary to Utilize the software alone. \n" \
     " * The patent license shall not apply to any combinations which include this software, \n" \
     " * other than combinations with devices manufactured by or for TI (\"TI Devices\"). \n" \
     " * No hardware patent is licensed hereunder. \n" \
     " * \n" \
     " * Redistributions must preserve existing copyright notices and reproduce this license \n" \
     " * (including the above copyright notice and the disclaimer and (if applicable) source \n" \
     " * code license limitations below) in the documentation and/or other materials provided \n" \
     " * with the distribution \n" \
     " * \n" \
     " * Redistribution and use in binary form, without modification, are permitted provided \n" \
     " * that the following conditions are met: \n" \
     " * \n" \
     " *        No reverse engineering, decompilation, or disassembly of this software is \n" \
     " * permitted with respect to any software provided in binary form. \n" \
     " * \n" \
     " *        any redistribution and use are licensed by TI for use only with TI Devices. \n" \
     " * \n" \
     " *        Nothing shall obligate TI to provide you with source code for the software \n" \
     " * licensed and provided to you in object code. \n" \
     " * \n" \
     " * If software source code is provided to you, modification and redistribution of the \n" \
     " * source code are permitted provided that the following conditions are met: \n" \
     " * \n" \
     " *        any redistribution and use of the source code, including any resulting derivative \n" \
     " * works, are licensed by TI for use only with TI Devices. \n" \
     " * \n" \
     " *        any redistribution and use of any object code compiled from the source code \n" \
     " * and any resulting derivative works, are licensed by TI for use only with TI Devices. \n" \
     " * \n" \
     " * Neither the name of Texas Instruments Incorporated nor the names of its suppliers \n" \
     " * \n" \
     " * may be used to endorse or promote products derived from this software without \n" \
     " * specific prior written permission. \n" \
     " * \n" \
     " * DISCLAIMER. \n" \
     " * \n" \
     " * THIS SOFTWARE IS PROVIDED BY TI AND TI'S LICENSORS \"AS IS\" AND ANY EXPRESS \n" \
     " * OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES \n" \
     " * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. \n" \
     " * IN NO EVENT SHALL TI AND TI'S LICENSORS BE LIABLE FOR ANY DIRECT, INDIRECT, \n" \
     " * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, \n" \
     " * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, \n" \
     " * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY \n" \
     " * OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE \n" \
     " * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED \n" \
     " * OF THE POSSIBILITY OF SUCH DAMAGE. \n" \
     " * \n" \
     " */ \n" 
    
    
