
#
# Steps to build DMAutils and VXLIB
#
# 1. copy this file to tiovx folder
# 2. Invoke make as below
#    make -s -j -fbuild_dmautils_vxlib.mk
#
include $(BUILD_SDK)_tools_path.mak

ifeq ($(OS),Windows_NT)
MAKE=gmake
else
MAKE=make
endif

VXLIB2_PATH = $(VSDK_INSTALL_PATH)/ti_components/algorithms/vxlib
DMAUTILS_PATH = $(VSDK_INSTALL_PATH)/ti_components/algorithms/dsp_apps/dmautils
ALGFRAMEWORK_PATH = $(VSDK_INSTALL_PATH)/ti_components/algorithms/dsp_apps/algframework

COPY=$(XDC_PATH)/bin/cp

VXLIB_OPTIONS=-C$(VXLIB2_PATH)
VXLIB_OPTIONS+=CGT6X_ROOT=$(CGT6X_ROOT)
VXLIB_OPTIONS+=ALGFRAMEWORK_ROOT=$(ALGFRAMEWORK_PATH)
VXLIB_OPTIONS+=DMAUTILS_ROOT=$(DMAUTILS_PATH)

VXLIB_C66_OPTIONS=$(VXLIB_OPTIONS) TARGET_CPU=C66 TARGET_SCPU=C66
VXLIB_X86_OPTIONS=$(VXLIB_OPTIONS) TARGET_CPU=X86 TARGET_SCPU=C66 TARGET_PLATFORM=PC HOST_COMPILER=GCC DIRECTORIES=ti/vxlib/src/

DMAUTILS_OPTIONS=-C$(DMAUTILS_PATH)/..
DMAUTILS_OPTIONS+=CGT6X_ROOT=$(CGT6X_ROOT)
DMAUTILS_OPTIONS+=ARP32CGT_ROOT=$(ARP32CGT_ROOT)
DMAUTILS_OPTIONS+=DMAUTILS_ROOT=$(DMAUTILS_PATH)
DMAUTILS_OPTIONS+=EDMA3_LLD_ROOT=$(EDMA3_LLD_PATH)
DMAUTILS_OPTIONS+=GCC_LINUX_ROOT=$(GCC_LINUX_ROOT)
DMAUTILS_OPTIONS+=GCC_WINDOWS_ROOT=$(GCC_WINDOWS_ROOT)


depend: dmautils vxlib 

vxlib_build:
#	$(MAKE) TARGET_BUILD=$(VXLIB_PROFILE) $(VXLIB_C66_OPTIONS) vxlib
#	$(MAKE) TARGET_BUILD=$(VXLIB_PROFILE) $(VXLIB_C66_OPTIONS) BAM_PLUGIN=1 vxlib_bamplugin
	$(MAKE) TARGET_BUILD=$(VXLIB_PROFILE) $(VXLIB_X86_OPTIONS) vxlib
	$(MAKE) TARGET_BUILD=$(VXLIB_PROFILE) $(VXLIB_X86_OPTIONS) BAM_PLUGIN=1 vxlib_bamplugin
	
vxlib:
	$(MAKE) -fMAKEFILE.MK vxlib_build VXLIB_PROFILE=debug
	$(MAKE) -fMAKEFILE.MK vxlib_build VXLIB_PROFILE=release

dmautils:
	$(MAKE) $(DMAUTILS_OPTIONS)



