grep -R -l "tivxDataRefQueueRelease" source/ | xargs sed -i 's/tivxDataRefQueueRelease/ownDataRefQueueRelease/g'
grep -R -l "tivxDataRefQueueGetObjDescId" source/ | xargs sed -i 's/tivxDataRefQueueGetObjDescId/ownDataRefQueueGetObjDescId/g'
grep -R -l "tivxDataRefQueueEnqueueReadyRef" source/ | xargs sed -i 's/tivxDataRefQueueEnqueueReadyRef/ownDataRefQueueEnqueueReadyRef/g'
grep -R -l "tivxDataRefQueueDequeueDoneRef" source/ | xargs sed -i 's/tivxDataRefQueueDequeueDoneRef/ownDataRefQueueDequeueDoneRef/g'
grep -R -l "tivxDataRefQueueWaitDoneRef" source/ | xargs sed -i 's/tivxDataRefQueueWaitDoneRef/ownDataRefQueueWaitDoneRef/g'
grep -R -l "tivxDataRefQueueGetDoneQueueCount" source/ | xargs sed -i 's/tivxDataRefQueueGetDoneQueueCount/ownDataRefQueueGetDoneQueueCount/g'
grep -R -l "tivxDataRefQueueGetReadyQueueCount" source/ | xargs sed -i 's/tivxDataRefQueueGetReadyQueueCount/ownDataRefQueueGetReadyQueueCount/g'
grep -R -l "tivxDataRefQueueSendRefConsumedEvent" source/ | xargs sed -i 's/tivxDataRefQueueSendRefConsumedEvent/ownDataRefQueueSendRefConsumedEvent/g'
grep -R -l "tivxDataRefQueueLinkDelayDataRefQueues" source/ | xargs sed -i 's/tivxDataRefQueueLinkDelayDataRefQueues/ownDataRefQueueLinkDelayDataRefQueues/g'

grep -R -l "tivxEventQueueCreate" source/ | xargs sed -i 's/tivxEventQueueCreate/ownEventQueueCreate/g'
grep -R -l "tivxEventQueueDelete" source/ | xargs sed -i 's/tivxEventQueueDelete/ownEventQueueDelete/g'
grep -R -l "tivxEventQueueAddEvent" source/ | xargs sed -i 's/tivxEventQueueAddEvent/ownEventQueueAddEvent/g'
grep -R -l "tivxEventQueueEnableEvents" source/ | xargs sed -i 's/tivxEventQueueEnableEvents/ownEventQueueEnableEvents/g'
grep -R -l "tivxRegisterEvent" source/ | xargs sed -i 's/tivxRegisterEvent/ownRegisterEvent/g'

grep -R -l "tivxIpcSendMsg" source/ | xargs sed -i 's/tivxIpcSendMsg/ownIpcSendMsg/g'
grep -R -l "tivxIpcRegisterHandler" source/ | xargs sed -i 's/tivxIpcRegisterHandler/ownIpcRegisterHandler/g'
grep -R -l "tivxIpcInit" source/ | xargs sed -i 's/tivxIpcInit/ownIpcInit/g'
grep -R -l "tivxIpcGetHostPortId" source/ | xargs sed -i 's/tivxIpcGetHostPortId/ownIpcGetHostPortId/g'
grep -R -l "tivxIpcDeInit" source/ | xargs sed -i 's/tivxIpcDeInit/ownIpcDeInit/g'

grep -R -l "tivxLogResourceInit" source/ | xargs sed -i 's/tivxLogResourceInit/ownLogResourceInit/g'
grep -R -l "tivxLogResourceDeInit" source/ | xargs sed -i 's/tivxLogResourceDeInit/ownLogResourceDeInit/g'
grep -R -l "tivxLogResourceAlloc" source/ | xargs sed -i 's/tivxLogResourceAlloc/ownLogResourceAlloc/g'
grep -R -l "tivxLogResourceFree" source/ | xargs sed -i 's/tivxLogResourceFree/ownLogResourceFree/g'
grep -R -l "tivxLogSetResourceUsedValue" source/ | xargs sed -i 's/tivxLogSetResourceUsedValue/ownLogSetResourceUsedValue/g'
grep -R -l "tivxLogRtInit" source/ | xargs sed -i 's/tivxLogRtInit/ownLogRtInit/g'
grep -R -l "tivxLogRtResetShm" source/ | xargs sed -i 's/tivxLogRtResetShm/ownLogRtResetShm/g'
grep -R -l "tivxLogRtTraceNodeExeStart" source/ | xargs sed -i 's/tivxLogRtTraceNodeExeStart/ownLogRtTraceNodeExeStart/g'
grep -R -l "tivxLogRtTraceNodeExeEnd" source/ | xargs sed -i 's/tivxLogRtTraceNodeExeEnd/ownLogRtTraceNodeExeEnd/g'
grep -R -l "tivxLogRtTraceGraphExeStart" source/ | xargs sed -i 's/tivxLogRtTraceGraphExeStart/ownLogRtTraceGraphExeStart/g'
grep -R -l "tivxLogRtTraceGraphExeEnd" source/ | xargs sed -i 's/tivxLogRtTraceGraphExeEnd/ownLogRtTraceGraphExeEnd/g'
grep -R -l "tivxLogRtTraceTargetExeStart" source/ | xargs sed -i 's/tivxLogRtTraceTargetExeStart/ownLogRtTraceTargetExeStart/g'
grep -R -l "tivxLogRtTraceTargetExeEnd" source/ | xargs sed -i 's/tivxLogRtTraceTargetExeEnd/ownLogRtTraceTargetExeEnd/g'

grep -R -l "tivxObjDescAlloc" source/ | xargs sed -i 's/tivxObjDescAlloc/ownObjDescAlloc/g'
grep -R -l "tivxObjDescFree" source/ | xargs sed -i 's/tivxObjDescFree/ownObjDescFree/g'
grep -R -l "tivxObjDescSend" source/ | xargs sed -i 's/tivxObjDescSend/ownObjDescSend/g'
grep -R -l "tivxObjDescGet" source/ | xargs sed -i 's/tivxObjDescGet/ownObjDescGet/g'
grep -R -l "tivxObjDescIsValidType" source/ | xargs sed -i 's/tivxObjDescIsValidType/ownObjDescIsValidType/g'
grep -R -l "tivxObjDescInit" source/ | xargs sed -i 's/tivxObjDescInit/ownObjDescInit/g'
grep -R -l "tivxReferenceGetObjDescId" source/ | xargs sed -i 's/tivxReferenceGetObjDescId/ownReferenceGetObjDescId/g'

grep -R -l "tivxObjDescQueueCreate" source/ | xargs sed -i 's/tivxObjDescQueueCreate/ownObjDescQueueCreate/g'
grep -R -l "tivxObjDescQueueRelease" source/ | xargs sed -i 's/tivxObjDescQueueRelease/ownObjDescQueueRelease/g'
grep -R -l "tivxObjDescQueueEnqueue" source/ | xargs sed -i 's/tivxObjDescQueueEnqueue/ownObjDescQueueEnqueue/g'
grep -R -l "tivxObjDescQueueGetCount" source/ | xargs sed -i 's/tivxObjDescQueueGetCount/ownObjDescQueueGetCount/g'
grep -R -l "tivxObjDescQueueDequeue" source/ | xargs sed -i 's/tivxObjDescQueueDequeue/ownObjDescQueueDequeue/g'
grep -R -l "tivxObjDescQueueAddBlockedNode" source/ | xargs sed -i 's/tivxObjDescQueueAddBlockedNode/ownObjDescQueueAddBlockedNode/g'
grep -R -l "tivxObjDescQueueExtractBlockedNodes" source/ | xargs sed -i 's/tivxObjDescQueueExtractBlockedNodes/ownObjDescQueueExtractBlockedNodes/g'

grep -R -l "tivxObjectAlloc" source/ | xargs sed -i 's/tivxObjectAlloc/ownObjectAlloc/g'
grep -R -l "tivxObjectFree" source/ | xargs sed -i 's/tivxObjectFree/ownObjectFree/g'
grep -R -l "tivxObjectInit" source/ | xargs sed -i 's/tivxObjectInit/ownObjectInit/g'
grep -R -l "tivxObjectDeInit" source/ | xargs sed -i 's/tivxObjectDeInit/ownObjectDeInit/g'

grep -R -l "tivxPlatformGetTargetId" source/ | xargs sed -i 's/tivxPlatformGetTargetId/ownPlatformGetTargetId/g'
grep -R -l "tivxPlatformGetTargetName" source/ | xargs sed -i 's/tivxPlatformGetTargetName/ownPlatformGetTargetName/g'
grep -R -l "tivxPlatformTargetMatch" source/ | xargs sed -i 's/tivxPlatformTargetMatch/ownPlatformTargetMatch/g'
grep -R -l "tivxPlatformGetObjDescTableInfo" source/ | xargs sed -i 's/tivxPlatformGetObjDescTableInfo/ownPlatformGetObjDescTableInfo/g'
grep -R -l "tivxPlatformGetLogRtShmInfo" source/ | xargs sed -i 's/tivxPlatformGetLogRtShmInfo/ownPlatformGetLogRtShmInfo/g'
grep -R -l "tivxPlatformSystemLock" source/ | xargs sed -i 's/tivxPlatformSystemLock/ownPlatformSystemLock/g'
grep -R -l "tivxPlatformSystemUnlock" source/ | xargs sed -i 's/tivxPlatformSystemUnlock/ownPlatformSystemUnlock/g'
grep -R -l "tivxPlatformInit" source/ | xargs sed -i 's/tivxPlatformInit/ownPlatformInit/g'
grep -R -l "tivxPlatformDeInit" source/ | xargs sed -i 's/tivxPlatformDeInit/ownPlatformDeInit/g'
grep -R -l "tivxPlatformPrintf" source/ | xargs sed -i 's/tivxPlatformPrintf/ownPlatformPrintf/g'
grep -R -l "tivxPlatformCreateTargets" source/ | xargs sed -i 's/tivxPlatformCreateTargets/ownPlatformCreateTargets/g'
grep -R -l "tivxPlatformDeleteTargets" source/ | xargs sed -i 's/tivxPlatformDeleteTargets/ownPlatformDeleteTargets/g'
grep -R -l "tivxPlatformActivate" source/ | xargs sed -i 's/tivxPlatformActivate/ownPlatformActivate/g'
grep -R -l "tivxPlatformDeactivate" source/ | xargs sed -i 's/tivxPlatformDeactivate/ownPlatformDeactivate/g'
grep -R -l "tivxPlatformGetDmaObj" source/ | xargs sed -i 's/tivxPlatformGetDmaObj/ownPlatformGetDmaObj/g'
grep -R -l "tivxPlatformTaskInit" source/ | xargs sed -i 's/tivxPlatformTaskInit/ownPlatformTaskInit/g'

grep -R -l "tivxTargetGetCpuId" source/ | xargs sed -i 's/tivxTargetGetCpuId/ownTargetGetCpuId/g'
grep -R -l "tivxTargetQueueObjDesc" source/ | xargs sed -i 's/tivxTargetQueueObjDesc/ownTargetQueueObjDesc/g'
grep -R -l "tivxTargetTriggerNode" source/ | xargs sed -i 's/tivxTargetTriggerNode/ownTargetTriggerNode/g'
grep -R -l "tivxTargetNodeDescAcquireAllParametersForPipeup" source/ | xargs sed -i 's/tivxTargetNodeDescAcquireAllParametersForPipeup/ownTargetNodeDescAcquireAllParametersForPipeup/g'

grep -R -l "tivxTargetNodeDescAcquireAllParameters" source/ | xargs sed -i 's/tivxTargetNodeDescAcquireAllParameters/ownTargetNodeDescAcquireAllParameters/g'
grep -R -l "tivxTargetNodeDescReleaseAllParameters" source/ | xargs sed -i 's/tivxTargetNodeDescReleaseAllParameters/ownTargetNodeDescReleaseAllParameters/g'
grep -R -l "tivxTargetSetDefaultCreateParams" source/ | xargs sed -i 's/tivxTargetSetDefaultCreateParams/ownTargetSetDefaultCreateParams/g'
grep -R -l "tivxTargetCreate" source/ | xargs sed -i 's/tivxTargetCreate/ownTargetCreate/g'
grep -R -l "tivxTargetDelete" source/ | xargs sed -i 's/tivxTargetDelete/ownTargetDelete/g'
grep -R -l "tivxTargetInit" source/ | xargs sed -i 's/tivxTargetInit/ownTargetInit/g'
grep -R -l "tivxTargetDeInit" source/ | xargs sed -i 's/tivxTargetDeInit/ownTargetDeInit/g'
grep -R -l "tivxTargetSetTimestamp" source/ | xargs sed -i 's/tivxTargetSetTimestamp/ownTargetSetTimestamp/g'

grep -R -l "tivxTargetKernelInstanceGetIndex" source/ | xargs sed -i 's/tivxTargetKernelInstanceGetIndex/ownTargetKernelInstanceGetIndex/g'
grep -R -l "tivxTargetKernelInstanceGet" source/ | xargs sed -i 's/tivxTargetKernelInstanceGet/ownTargetKernelInstanceGet/g'
grep -R -l "tivxTargetKernelInstanceAlloc" source/ | xargs sed -i 's/tivxTargetKernelInstanceAlloc/ownTargetKernelInstanceAlloc/g'
grep -R -l "tivxTargetKernelInstanceFree" source/ | xargs sed -i 's/tivxTargetKernelInstanceFree/ownTargetKernelInstanceFree/g'
grep -R -l "tivxTargetKernelInstanceInit" source/ | xargs sed -i 's/tivxTargetKernelInstanceInit/ownTargetKernelInstanceInit/g'
grep -R -l "tivxTargetKernelInstanceDeInit" source/ | xargs sed -i 's/tivxTargetKernelInstanceDeInit/ownTargetKernelInstanceDeInit/g'
grep -R -l "ownTargetKernelInstanceGetKernel" source/ | xargs sed -i 's/ownTargetKernelInstanceGetKernel/tivxTargetKernelInstanceGetKernel/g'

grep -R -l "tivxTargetKernelExecute" source/ | xargs sed -i 's/tivxTargetKernelExecute/ownTargetKernelExecute/g'
grep -R -l "tivxTargetKernelCreate" source/ | xargs sed -i 's/tivxTargetKernelCreate/ownTargetKernelCreate/g'
grep -R -l "tivxTargetKernelDelete" source/ | xargs sed -i 's/tivxTargetKernelDelete/ownTargetKernelDelete/g'
grep -R -l "tivxTargetKernelControl" source/ | xargs sed -i 's/tivxTargetKernelControl/ownTargetKernelControl/g'
grep -R -l "tivxTargetKernelGet" source/ | xargs sed -i 's/tivxTargetKernelGet/ownTargetKernelGet/g'
grep -R -l "tivxTargetKernelInit" source/ | xargs sed -i 's/tivxTargetKernelInit/ownTargetKernelInit/g'
grep -R -l "tivxTargetKernelDeInit" source/ | xargs sed -i 's/tivxTargetKernelDeInit/ownTargetKernelDeInit/g'
