grep -R -l "tivxDataRefQueueDestruct" source/ | xargs sed -i 's/tivxDataRefQueueDestruct/ownDataRefQueueDestruct/g'

grep -R -l "tivxExportGraphTopLevelToDot" source/ | xargs sed -i 's/tivxExportGraphTopLevelToDot/ownExportGraphTopLevelToDot/g'
grep -R -l "tivxExportGraphDataRefQueueToDot" source/ | xargs sed -i 's/tivxExportGraphDataRefQueueToDot/ownExportGraphDataRefQueueToDot/g'
grep -R -l "tivxExportGraphDataRefQueuesToDot" source/ | xargs sed -i 's/tivxExportGraphDataRefQueuesToDot/ownExportGraphDataRefQueuesToDot/g'
grep -R -l "tivxExportGraphFirstPipelineToDot" source/ | xargs sed -i 's/tivxExportGraphFirstPipelineToDot/ownExportGraphFirstPipelineToDot/g'
grep -R -l "tivxExportGraphPipelineToDot" source/ | xargs sed -i 's/tivxExportGraphPipelineToDot/ownExportGraphPipelineToDot/g'

grep -R -l "tivxGraphSortStackReset" source/ | xargs sed -i 's/tivxGraphSortStackReset/ownGraphSortStackReset/g'
grep -R -l "tivxGraphSortStackPush" source/ | xargs sed -i 's/tivxGraphSortStackPush/ownGraphSortStackPush/g'
grep -R -l "tivxGraphSortStackPop" source/ | xargs sed -i 's/tivxGraphSortStackPop/ownGraphSortStackPop/g'

grep -R -l "tivxStreamingNoPipeliningTask" source/ | xargs sed -i 's/tivxStreamingNoPipeliningTask/ownStreamingNoPipeliningTask/g'
grep -R -l "tivxStreamingPipeliningTask" source/ | xargs sed -i 's/tivxStreamingPipeliningTask/ownStreamingPipeliningTask/g'

grep -R -l "tivxLogRtTraceFindEventId" source/ | xargs sed -i 's/tivxLogRtTraceFindEventId/ownLogRtTraceFindEventId/g'
grep -R -l "tivxLogRtTraceFindEventName" source/ | xargs sed -i 's/tivxLogRtTraceFindEventName/ownLogRtTraceFindEventName/g'
grep -R -l "tivxLogRtTraceAddEventClass" source/ | xargs sed -i 's/tivxLogRtTraceAddEventClass/ownLogRtTraceAddEventClass/g'
grep -R -l "tivxLogRtFileWrite" source/ | xargs sed -i 's/tivxLogRtFileWrite/ownLogRtFileWrite/g'
grep -R -l "tivxLogRtTraceLogEvent" source/ | xargs sed -i 's/tivxLogRtTraceLogEvent/ownLogRtTraceLogEvent/g'
grep -R -l "tivxLogRtTraceSetup" source/ | xargs sed -i 's/tivxLogRtTraceSetup/ownLogRtTraceSetup/g'

grep -R -l "tivxIpcPayloadMake" source/ | xargs sed -i 's/tivxIpcPayloadMake/ownIpcPayloadMake/g'
grep -R -l "tivxIpcPayloadGetObjDescId" source/ | xargs sed -i 's/tivxIpcPayloadGetObjDescId/ownIpcPayloadGetObjDescId/g'
grep -R -l "tivxIpcPayloadGetTargetId" source/ | xargs sed -i 's/tivxIpcPayloadGetTargetId/ownIpcPayloadGetTargetId/g'
grep -R -l "tivxObjDescIpcHandler" source/ | xargs sed -i 's/tivxObjDescIpcHandler/ownObjDescIpcHandler/g'

grep -R -l "tivxObjDescQueueReset" source/ | xargs sed -i 's/tivxObjDescQueueReset/ownObjDescQueueReset/g'

grep -R -l "tivxTargetAllocHandle" source/ | xargs sed -i 's/tivxTargetAllocHandle/ownTargetAllocHandle/g'
grep -R -l "tivxTargetFreeHandle" source/ | xargs sed -i 's/tivxTargetFreeHandle/ownTargetFreeHandle/g'
grep -R -l "tivxTargetDequeueObjDesc" source/ | xargs sed -i 's/tivxTargetDequeueObjDesc/ownTargetDequeueObjDesc/g'
grep -R -l "tivxTargetGetHandle" source/ | xargs sed -i 's/tivxTargetGetHandle/ownTargetGetHandle/g'
grep -R -l "tivxTargetNodeDescSendComplete" source/ | xargs sed -i 's/tivxTargetNodeDescSendComplete/ownTargetNodeDescSendComplete/g'
grep -R -l "tivxTargetNodeDescCanNodeExecute" source/ | xargs sed -i 's/tivxTargetNodeDescCanNodeExecute/ownTargetNodeDescCanNodeExecute/g'
grep -R -l "tivxTargetNodeDescTriggerNextNodes" source/ | xargs sed -i 's/tivxTargetNodeDescTriggerNextNodes/ownTargetNodeDescTriggerNextNodes/g'
grep -R -l "tivxTargetNodeDescNodeExecuteTargetKernel" source/ | xargs sed -i 's/tivxTargetNodeDescNodeExecuteTargetKernel/ownTargetNodeDescNodeExecuteTargetKernel/g'
grep -R -l "tivxTargetNodeDescNodeExecuteUserKernel" source/ | xargs sed -i 's/tivxTargetNodeDescNodeExecuteUserKernel/ownTargetNodeDescNodeExecuteUserKernel/g'
grep -R -l "tivxTargetNodeDescIsPrevPipeNodeBlocked" source/ | xargs sed -i 's/tivxTargetNodeDescIsPrevPipeNodeBlocked/ownTargetNodeDescIsPrevPipeNodeBlocked/g'
grep -R -l "tivxTargetNodeDescNodeMarkComplete" source/ | xargs sed -i 's/tivxTargetNodeDescNodeMarkComplete/ownTargetNodeDescNodeMarkComplete/g'
grep -R -l "tivxTargetNodeDescNodeExecute" source/ | xargs sed -i 's/tivxTargetNodeDescNodeExecute/ownTargetNodeDescNodeExecute/g'
grep -R -l "tivxTargetNodeDescNodeCreate" source/ | xargs sed -i 's/tivxTargetNodeDescNodeCreate/ownTargetNodeDescNodeCreate/g'
grep -R -l "tivxTargetNodeDescNodeDelete" source/ | xargs sed -i 's/tivxTargetNodeDescNodeDelete/ownTargetNodeDescNodeDelete/g'
grep -R -l "tivxTargetNodeSendCommand" source/ | xargs sed -i 's/tivxTargetNodeSendCommand/ownTargetNodeSendCommand/g'
grep -R -l "tivxTargetNodeDescNodeControl" source/ | xargs sed -i 's/tivxTargetNodeDescNodeControl/ownTargetNodeDescNodeControl/g'
grep -R -l "tivxTargetCmdDescHandleAck" source/ | xargs sed -i 's/tivxTargetCmdDescHandleAck/ownTargetCmdDescHandleAck/g'
grep -R -l "tivxTargetCmdDescHandleUserCallback" source/ | xargs sed -i 's/tivxTargetCmdDescHandleUserCallback/ownTargetCmdDescHandleUserCallback/g'
grep -R -l "tivxTargetSetGraphStateAbandon" source/ | xargs sed -i 's/tivxTargetSetGraphStateAbandon/ownTargetSetGraphStateAbandon/g'
grep -R -l "tivxTargetCmdDescSendAck" source/ | xargs sed -i 's/tivxTargetCmdDescSendAck/ownTargetCmdDescSendAck/g'
grep -R -l "tivxTargetCmdDescHandler" source/ | xargs sed -i 's/tivxTargetCmdDescHandler/ownTargetCmdDescHandler/g'
grep -R -l "tivxTargetTaskMain" source/ | xargs sed -i 's/tivxTargetTaskMain/ownTargetTaskMain/g'
grep -R -l "tivxTargetObjDescSendRefConsumed" source/ | xargs sed -i 's/tivxTargetObjDescSendRefConsumed/ownTargetObjDescSendRefConsumed/g'
grep -R -l "tivxTargetNodeDescAcquireParameterForPipeup" source/ | xargs sed -i 's/tivxTargetNodeDescAcquireParameterForPipeup/ownTargetNodeDescAcquireParameterForPipeup/g'
grep -R -l "tivxTargetNodeDescAcquireParameter" source/ | xargs sed -i 's/tivxTargetNodeDescAcquireParameter/ownTargetNodeDescAcquireParameter/g'
grep -R -l "tivxTargetNodeDescReleaseParameterInDelay" source/ | xargs sed -i 's/tivxTargetNodeDescReleaseParameterInDelay/ownTargetNodeDescReleaseParameterInDelay/g'
grep -R -l "tivxTargetNodeDescReleaseParameter" source/ | xargs sed -i 's/tivxTargetNodeDescReleaseParameter/ownTargetNodeDescReleaseParameter/g'

grep -R -l "tivxAddTargetKernelInternal" source/ | xargs sed -i 's/tivxAddTargetKernelInternal/ownAddTargetKernelInternal/g'
