/* 
 * This file is AUTO GENERATED by PyTI_PSDK_RTOS tool. 
 * It is NOT recommended to manually edit this file 
 */ 
/* 
 * 
 * Copyright (c) 2018 Texas Instruments Incorporated 
 * 
 * All rights reserved not granted herein. 
 * 
 * Limited License. 
 * 
 * Texas Instruments Incorporated grants a world-wide, royalty-free, non-exclusive 
 * license under copyrights and patents it now or hereafter owns or controls to make, 
 * have made, use, import, offer to sell and sell ("Utilize") this software subject to the 
 * terms herein.  With respect to the foregoing patent license, such license is granted 
 * solely to the extent that any such patent is necessary to Utilize the software alone. 
 * The patent license shall not apply to any combinations which include this software, 
 * other than combinations with devices manufactured by or for TI ("TI Devices"). 
 * No hardware patent is licensed hereunder. 
 * 
 * Redistributions must preserve existing copyright notices and reproduce this license 
 * (including the above copyright notice and the disclaimer and (if applicable) source 
 * code license limitations below) in the documentation and/or other materials provided 
 * with the distribution 
 * 
 * Redistribution and use in binary form, without modification, are permitted provided 
 * that the following conditions are met: 
 * 
 *        No reverse engineering, decompilation, or disassembly of this software is 
 * permitted with respect to any software provided in binary form. 
 * 
 *        any redistribution and use are licensed by TI for use only with TI Devices. 
 * 
 *        Nothing shall obligate TI to provide you with source code for the software 
 * licensed and provided to you in object code. 
 * 
 * If software source code is provided to you, modification and redistribution of the 
 * source code are permitted provided that the following conditions are met: 
 * 
 *        any redistribution and use of the source code, including any resulting derivative 
 * works, are licensed by TI for use only with TI Devices. 
 * 
 *        any redistribution and use of any object code compiled from the source code 
 * and any resulting derivative works, are licensed by TI for use only with TI Devices. 
 * 
 * Neither the name of Texas Instruments Incorporated nor the names of its suppliers 
 * 
 * may be used to endorse or promote products derived from this software without 
 * specific prior written permission. 
 * 
 * DISCLAIMER. 
 * 
 * THIS SOFTWARE IS PROVIDED BY TI AND TI'S LICENSORS "AS IS" AND ANY EXPRESS 
 * OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES 
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. 
 * IN NO EVENT SHALL TI AND TI'S LICENSORS BE LIABLE FOR ANY DIRECT, INDIRECT, 
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, 
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, 
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY 
 * OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE 
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED 
 * OF THE POSSIBILITY OF SUCH DAMAGE. 
 * 
 */ 
#ifndef APP_MEM_MAP_H
#define APP_MEM_MAP_H


/* MSMC for MPU1 [ size 64.00 KB ] */
#define MSMC_MPU1_ADDR (0x70000000u)
#define MSMC_MPU1_SIZE (0x00010000u)

/* MSMC for C7x_1 [ size  7.88 MB ] */
#define MSMC_C7x_1_ADDR (0x70010000u)
#define MSMC_C7x_1_SIZE (0x007E0000u)

/* DDR for MPU1   for code/data [ size 160.00 MB ] */
#define DDR_MPU1_ADDR (0x80000000u)
#define DDR_MPU1_SIZE (0x0A000000u)

/* DDR for C66x_1 for code/data [ size 64.00 MB ] */
#define DDR_C66x_1_ADDR (0x8A000000u)
#define DDR_C66x_1_SIZE (0x04000000u)

/* DDR for C66x_2 for code/data [ size 16.00 MB ] */
#define DDR_C66x_2_ADDR (0x8E000000u)
#define DDR_C66x_2_SIZE (0x01000000u)

/* DDR for C7x_1  for boot code [ size 64.00 KB ] */
#define DDR_C7x_1_BOOT_ADDR (0x8F000000u)
#define DDR_C7x_1_BOOT_SIZE (0x00010000u)

/* DDR for C7x_1  for code/data [ size 127.94 MB ] */
#define DDR_C7x_1_ADDR (0x8F010000u)
#define DDR_C7x_1_SIZE (0x07FF0000u)

/* DDR for MCU2_1 for code/data [ size 64.00 MB ] */
#define DDR_MCU2_1_ADDR (0x9B000000u)
#define DDR_MCU2_1_SIZE (0x04000000u)

/* Non-cached memory [ size 64.00 MB ] */
#define NON_CACHED_MEM_ADDR (0xA3000000u)
#define NON_CACHED_MEM_SIZE (0x04000000u)

/* Memory for shared memory buffers in DDR [ size 400.00 MB ] */
#define DDR_SHARED_MEM_ADDR (0xA7000000u)
#define DDR_SHARED_MEM_SIZE (0x19000000u)


#endif /* APP_MEM_MAP_H */

